# Generated by Django 3.0.6 on 2020-05-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalPacjenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placówka',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portalPacjenta.Pacjent'),
        ),
    ]
