# Generated by Django 3.0.6 on 2020-05-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalPacjenta', '0002_auto_20200504_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='konsultacja',
            name='description',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
