# Generated by Django 3.0.6 on 2020-05-07 09:14

from django.db import migrations, models
import portalPacjenta.models


class Migration(migrations.Migration):

    dependencies = [
        ('portalPacjenta', '0007_auto_20200506_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='konsultacja',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='konsultacja',
            name='date',
            field=models.DateField(validators=[portalPacjenta.models.date_validation]),
        ),
    ]
