# Generated by Django 3.0.6 on 2020-05-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalPacjenta', '0008_auto_20200507_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konsultacja',
            name='place',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='portalPacjenta.Placówka'),
            preserve_default=False,
        ),
    ]
