# Generated by Django 3.0.6 on 2020-05-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalPacjenta', '0009_auto_20200507_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='konsultacja',
            name='time',
            field=models.TimeField(default='16:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profil',
            name='phone',
            field=models.CharField(max_length=18),
        ),
    ]
